#!/usr/bin/env Rscript

# Phase 04 - Step 02: Degree & Distribution Metrics
# -------------------------------------------------
# Purpose:
#   Compute and characterize degree sequences for both FG-level and STR-level
#   bipartite networks. Generate summary statistics and distribution plots.
#
# Responsibilities:
#   1. Load preflight validation and adjacency matrices
#   2. Compute degree vectors:
#      - Producer out-degree (agents -> pyovs)
#      - Consumer in-degree (pyovs -> agents)
#      - Pyov production in-degree and utilization out-degree
#   3. Generate summary statistics (min, median, mean, max, SD, quantiles)
#   4. Create degree histograms and CCDF plots (log-scale for heavy-tail analysis)
#   5. Save consolidated metrics and figures
#
# Outputs:
#   - results/phase_04/degree/degree_metrics_fg.rds
#   - results/phase_04/degree/degree_metrics_str.rds
#   - figures/network_topology/degree_dist_fg_producer.pdf
#   - figures/network_topology/degree_dist_fg_consumer.pdf
#   - figures/network_topology/degree_dist_str_producer.pdf
#   - figures/network_topology/degree_dist_str_consumer.pdf
#   - figures/network_topology/degree_ccdf_fg.pdf
#   - figures/network_topology/degree_ccdf_str.pdf
#   - docs/phase_04/logs/step02_degree_summary.txt
#
# Usage:
#   Rscript scripts/phase_04_topology/02_degree_and_distributions.R
#
# Dependencies: base R, Matrix, ggplot2, dplyr, tidyr
#
# Author: automated assistant
# Date: autogenerated

suppressPackageStartupMessages({
  library(Matrix)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(readr)
})

# -----------------------------
# Helper functions
# -----------------------------
safe_dir_create <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE, showWarnings = FALSE)
}

timestamp <- function() format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")

# Compute comprehensive degree statistics
compute_degree_stats <- function(degrees) {
  stats <- list(
    n = length(degrees),
    min = min(degrees),
    q25 = quantile(degrees, 0.25),
    median = median(degrees),
    q75 = quantile(degrees, 0.75),
    mean = mean(degrees),
    max = max(degrees),
    sd = sd(degrees),
    zeros = sum(degrees == 0),
    nonzero = sum(degrees > 0)
  )
  stats$proportion_nonzero = stats$nonzero / stats$n
  return(stats)
}

# Create degree histogram plot
plot_degree_histogram <- function(degrees, title, xlabel, ylabel = "Count") {
  df <- data.frame(degree = degrees)
  ggplot(df, aes(x = degree)) +
    geom_histogram(binwidth = 1, fill = "steelblue", color = "black", alpha = 0.7) +
    labs(title = title, x = xlabel, y = ylabel) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
}

# Create CCDF plot (Complementary Cumulative Distribution Function)
plot_ccdf <- function(degrees, title, xlabel) {
  # Remove zeros for log-scale visualization
  nonzero_degrees <- degrees[degrees > 0]
  if (length(nonzero_degrees) == 0) {
    # Return empty plot if no non-zero degrees
    return(ggplot() + theme_void() +
           annotate("text", x = 0.5, y = 0.5, label = "No non-zero degrees", size = 4))
  }

  # Sort degrees in descending order
  sorted_degrees <- sort(nonzero_degrees, decreasing = TRUE)
  n <- length(sorted_degrees)
  ccdf <- data.frame(
    degree = sorted_degrees,
    probability = (1:n) / n  # P(X >= x)
  )

  ggplot(ccdf, aes(x = degree, y = probability)) +
    geom_line(color = "red", size = 1) +
    geom_point(color = "red", size = 0.5, alpha = 0.6) +
    scale_x_log10() +
    scale_y_log10() +
    labs(title = title, x = paste(xlabel, "(log scale)"),
         y = "P(X ≥ degree) (log scale)") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
}

# -----------------------------
# Directory setup
# -----------------------------
safe_dir_create("results/phase_04/degree")
safe_dir_create("figures/network_topology")
safe_dir_create("docs/phase_04/logs")

# -----------------------------
# Load preflight validation and data
# -----------------------------
cat("Loading preflight validation and adjacency matrices...\n")

# Check preflight status
preflight_path <- "results/phase_04/preflight_status.rds"
if (!file.exists(preflight_path)) {
  stop("Preflight validation not found. Run Step 01 first.")
}

preflight <- readRDS(preflight_path)
if (preflight$critical_failures > 0) {
  stop("Critical failures detected in preflight. Resolve before proceeding.")
}

# Load adjacency matrices
adj_prod_fg <- readRDS("data/interim/adj_production_FG_agentsxpyov_conservative.rds")
adj_util_fg <- readRDS("data/interim/adj_utilization_FG_pyovxagents_conservative.rds")
adj_prod_str <- readRDS("data/interim/adj_production_STR_agentsxpyov_conservative.rds")
adj_util_str <- readRDS("data/interim/adj_utilization_STR_pyovxagents_conservative.rds")

# Load node tables for reference
fg_nodes <- readRDS("data/interim/nodes_functional_groups_conservative.rds")
str_nodes <- readRDS("data/interim/nodes_strains_conservative.rds")
pyov_nodes <- readRDS("data/interim/nodes_pyoverdines_conservative.rds")

cat("Data loaded successfully.\n")

# -----------------------------
# Compute degree vectors - FG level
# -----------------------------
cat("Computing FG-level degree sequences...\n")

# Producer out-degree: FG -> PYOV (row sums of production matrix)
fg_producer_out <- as.integer(Matrix::rowSums(adj_prod_fg))
names(fg_producer_out) <- rownames(adj_prod_fg)

# Consumer in-degree: PYOV -> FG (col sums of utilization matrix)
fg_consumer_in <- as.integer(Matrix::colSums(adj_util_fg))
names(fg_consumer_in) <- colnames(adj_util_fg)

# Pyov production in-degree (how many FGs produce each pyov)
pyov_prod_in_fg <- as.integer(Matrix::colSums(adj_prod_fg))
names(pyov_prod_in_fg) <- colnames(adj_prod_fg)

# Pyov utilization out-degree (how many FGs utilize each pyov)
pyov_util_out_fg <- as.integer(Matrix::rowSums(adj_util_fg))
names(pyov_util_out_fg) <- rownames(adj_util_fg)

# Compute statistics
fg_stats <- list(
  producer_out = compute_degree_stats(fg_producer_out),
  consumer_in = compute_degree_stats(fg_consumer_in),
  pyov_prod_in = compute_degree_stats(pyov_prod_in_fg),
  pyov_util_out = compute_degree_stats(pyov_util_out_fg)
)

# Create degree vectors object
fg_degrees <- list(
  fg_producer_out = fg_producer_out,
  fg_consumer_in = fg_consumer_in,
  pyov_prod_in = pyov_prod_in_fg,
  pyov_util_out = pyov_util_out_fg,
  stats = fg_stats,
  metadata = list(
    n_fg = nrow(fg_nodes),
    n_pyov = nrow(pyov_nodes),
    timestamp = timestamp()
  )
)

# -----------------------------
# Compute degree vectors - STR level
# -----------------------------
cat("Computing STR-level degree sequences...\n")

# Producer out-degree: STR -> PYOV
str_producer_out <- as.integer(Matrix::rowSums(adj_prod_str))
names(str_producer_out) <- rownames(adj_prod_str)

# Consumer in-degree: PYOV -> STR
str_consumer_in <- as.integer(Matrix::colSums(adj_util_str))
names(str_consumer_in) <- colnames(adj_util_str)

# Pyov production in-degree (strain-level)
pyov_prod_in_str <- as.integer(Matrix::colSums(adj_prod_str))
names(pyov_prod_in_str) <- colnames(adj_prod_str)

# Pyov utilization out-degree (strain-level)
pyov_util_out_str <- as.integer(Matrix::rowSums(adj_util_str))
names(pyov_util_out_str) <- rownames(adj_util_str)

# Compute statistics
str_stats <- list(
  producer_out = compute_degree_stats(str_producer_out),
  consumer_in = compute_degree_stats(str_consumer_in),
  pyov_prod_in = compute_degree_stats(pyov_prod_in_str),
  pyov_util_out = compute_degree_stats(pyov_util_out_str)
)

# Create degree vectors object
str_degrees <- list(
  str_producer_out = str_producer_out,
  str_consumer_in = str_consumer_in,
  pyov_prod_in = pyov_prod_in_str,
  pyov_util_out = pyov_util_out_str,
  stats = str_stats,
  metadata = list(
    n_str = nrow(str_nodes),
    n_pyov = nrow(pyov_nodes),
    timestamp = timestamp()
  )
)

# -----------------------------
# Save degree metrics
# -----------------------------
cat("Saving degree metrics...\n")

saveRDS(fg_degrees, "results/phase_04/degree/degree_metrics_fg.rds")
saveRDS(str_degrees, "results/phase_04/degree/degree_metrics_str.rds")

# -----------------------------
# Generate plots - FG level
# -----------------------------
cat("Generating FG-level degree plots...\n")

# Producer out-degree histogram
p_fg_prod_hist <- plot_degree_histogram(
  fg_producer_out,
  "FG Producer Out-Degree Distribution",
  "Number of Pyoverdines Produced"
)
ggsave("figures/network_topology/degree_dist_fg_producer.pdf", p_fg_prod_hist, width = 8, height = 6)

# Consumer in-degree histogram
p_fg_cons_hist <- plot_degree_histogram(
  fg_consumer_in,
  "FG Consumer In-Degree Distribution",
  "Number of Pyoverdines Utilized"
)
ggsave("figures/network_topology/degree_dist_fg_consumer.pdf", p_fg_cons_hist, width = 8, height = 6)

# CCDF plots for FG
p_fg_ccdf_prod <- plot_ccdf(
  fg_producer_out,
  "FG Producer Out-Degree CCDF",
  "Producer Out-Degree"
)
p_fg_ccdf_cons <- plot_ccdf(
  fg_consumer_in,
  "FG Consumer In-Degree CCDF",
  "Consumer In-Degree"
)

# Combine CCDF plots
library(patchwork)
p_fg_ccdf_combined <- (p_fg_ccdf_prod + p_fg_ccdf_cons) +
  plot_layout(ncol = 2) +
  plot_annotation(title = "FG-Level Degree CCDFs")
ggsave("figures/network_topology/degree_ccdf_fg.pdf", p_fg_ccdf_combined, width = 12, height = 5)

# -----------------------------
# Generate plots - STR level
# -----------------------------
cat("Generating STR-level degree plots...\n")

# Producer out-degree histogram
p_str_prod_hist <- plot_degree_histogram(
  str_producer_out,
  "Strain Producer Out-Degree Distribution",
  "Number of Pyoverdines Produced"
)
ggsave("figures/network_topology/degree_dist_str_producer.pdf", p_str_prod_hist, width = 8, height = 6)

# Consumer in-degree histogram
p_str_cons_hist <- plot_degree_histogram(
  str_consumer_in,
  "Strain Consumer In-Degree Distribution",
  "Number of Pyoverdines Utilized"
)
ggsave("figures/network_topology/degree_dist_str_consumer.pdf", p_str_cons_hist, width = 8, height = 6)

# CCDF plots for STR
p_str_ccdf_prod <- plot_ccdf(
  str_producer_out,
  "Strain Producer Out-Degree CCDF",
  "Producer Out-Degree"
)
p_str_ccdf_cons <- plot_ccdf(
  str_consumer_in,
  "Strain Consumer In-Degree CCDF",
  "Consumer In-Degree"
)

# Combine CCDF plots
p_str_ccdf_combined <- (p_str_ccdf_prod + p_str_ccdf_cons) +
  plot_layout(ncol = 2) +
  plot_annotation(title = "Strain-Level Degree CCDFs")
ggsave("figures/network_topology/degree_ccdf_str.pdf", p_str_ccdf_combined, width = 12, height = 5)

# -----------------------------
# Generate summary report
# -----------------------------
cat("Generating summary report...\n")

summary_lines <- c(
  "Phase 04 - Step 02: Degree & Distribution Metrics Summary",
  paste("Timestamp:", timestamp()),
  "",
  "Functional Group (FG) Level:",
  sprintf("  Nodes: %d FGs, %d Pyovs", fg_degrees$metadata$n_fg, fg_degrees$metadata$n_pyov),
  sprintf("  Producer out-degree: mean=%.2f, median=%.1f, max=%d, zeros=%d",
          fg_stats$producer_out$mean, fg_stats$producer_out$median,
          fg_stats$producer_out$max, fg_stats$producer_out$zeros),
  sprintf("  Consumer in-degree: mean=%.2f, median=%.1f, max=%d, zeros=%d",
          fg_stats$consumer_in$mean, fg_stats$consumer_in$median,
          fg_stats$consumer_in$max, fg_stats$consumer_in$zeros),
  sprintf("  Pyov production in-degree: mean=%.2f, median=%.1f, max=%d",
          fg_stats$pyov_prod_in$mean, fg_stats$pyov_prod_in$median,
          fg_stats$pyov_prod_in$max),
  sprintf("  Pyov utilization out-degree: mean=%.2f, median=%.1f, max=%d",
          fg_stats$pyov_util_out$mean, fg_stats$pyov_util_out$median,
          fg_stats$pyov_util_out$max),
  "",
  "Strain (STR) Level:",
  sprintf("  Nodes: %d Strains, %d Pyovs", str_degrees$metadata$n_str, str_degrees$metadata$n_pyov),
  sprintf("  Producer out-degree: mean=%.2f, median=%.1f, max=%d, zeros=%d",
          str_stats$producer_out$mean, str_stats$producer_out$median,
          str_stats$producer_out$max, str_stats$producer_out$zeros),
  sprintf("  Consumer in-degree: mean=%.2f, median=%.1f, max=%d, zeros=%d",
          str_stats$consumer_in$mean, str_stats$consumer_in$median,
          str_stats$consumer_in$max, str_stats$consumer_in$zeros),
  sprintf("  Pyov production in-degree: mean=%.2f, median=%.1f, max=%d",
          str_stats$pyov_prod_in$mean, str_stats$pyov_prod_in$median,
          str_stats$pyov_prod_in$max),
  sprintf("  Pyov utilization out-degree: mean=%.2f, median=%.1f, max=%d",
          str_stats$pyov_util_out$mean, str_stats$pyov_util_out$median,
          str_stats$pyov_util_out$max),
  "",
  "Outputs saved:",
  "  - results/phase_04/degree/degree_metrics_fg.rds",
  "  - results/phase_04/degree/degree_metrics_str.rds",
  "  - figures/network_topology/degree_dist_*.pdf (histograms)",
  "  - figures/network_topology/degree_ccdf_*.pdf (CCDF plots)",
  "",
  "Ready for Step 03: Modularity Analysis."
)

writeLines(summary_lines, "docs/phase_04/logs/step02_degree_summary.txt")
cat(paste(summary_lines, collapse = "\n"), "\n")

# Save session info
writeLines(capture.output(sessionInfo()), "docs/phase_04/logs/step02_session_info.txt")

cat("Step 02 complete. Degree metrics and distributions computed.\n")
